### ISSUE TITLE
Pricing model for Pro

### ISSUE THREAD

**Issue by tj** [apex/up#2]
I haven't decided on this yet, likely tiered, I'd be happy if small companies with little funding don't have to pay much, startups and established companies can afford more. Perhaps by company size? Maybe just by feature-set, we'll see, happy to hear suggestions!

Recording the time required to create Up, that might help gauge how much time it would save someone as well haha, most teams should not be wasting time developing tooling, engineers are pricey!

**Comment by jonotron** [comment]
I don't know a whole lot about how Up is going to work (doesn't seem like SaaS, more like Apex++). I really like the Sketch pricing model... possibly per user to scale better with company size?

**Comment by tj** [comment]
Yup! It's basically apex(1) but for apps/sites/apis instead of event processing. I like the idea of maybe even skipping a Pro version and licensing based on the size, but I imagine many people might just go ahead and not pay haha

**Comment by lukeed** [comment]
How about capping projects? Any option is bound to make _someone_ upset, but capping the total number of deployed projects seems like the most straightforward/honest metric.

Since Up is a self-hosted service, will be charging for every new app it's bootstrapped.
Eg: `free` -> 5 active apps; `foo` -> 10 active apps; `pro` -> unlimited active + unlocked features

**Comment by tj** [comment]
@lukeed that might make sense, I suppose I'd have to have a way to "trial" the pro stuff anyway. Individuals tend to not care about licensing anyway, companies definitely do, so it might be a lost cause at the lower end haha.

**Comment by lukeed** [comment]
Saw the edit -- like the sound of that. Nice & simple 👍 

Would like to make two more suggestions:

1. Upgrade & downgrade from Pro whenever, assuming total-active-deployments limit is not surpassed

2. Add a `Pay As You Go` plan for people who have surpassed the `"foo"` limit (eg 10) but don't necessarily care for/need the `"pro"` features. At this point (hypothetically), you're only charging for convenience of managing deployments, it can be another straightforward pricing model of $3 per additional active project. You've got to play with the charges, ofc, but at some point it'll just make sense to go to the `pro` plan for unlimited deployments alone.

**Comment by tj** [comment]
I'll be adding quite a few time-saving value-adding features as well hopefully. I'll give it some more thought, http://sidekiq.org's model is working really well for him, I think it's pretty fair to take a decent chunk from huge companies to make the project sustainable, they don't flinch at stuff like that.

**Comment by lukeed** [comment]
You bet! You gotta do what works best for you, first and foremost. Just tossing around ideas

**Comment by tj** [comment]
Appreciate it! Definitely new to this side of things

**Comment by jkroso** [comment]
Maybe charge per feature, assuming it will be subscriptions you sell. People who really don't care about pricing will just click select all. And BTW I think everyone should pay at least a little bit. It's more important that projects like this get done than that they be free. Maybe support a `--please` flag which voids the need for a subscription for people who are trying it out or really can't afford anything.

**Comment by tj** [comment]
@jkroso yeah I wonder if drawing the line at commercial use regardless of community/pro version makes sense. It would be nice not to manage two distinct versions.

**Comment by jkroso** [comment]
Yeah that would work. But eventually I think you should just charge the marginal cost. Charging by feature enables you to drop the cost of old features while still having an incentive to pursue new features.

**Comment by jorinvo** [comment]
A pricing model similar to Caddy might also interesting for up: https://caddyserver.com/pricing

**Comment by badslug** [comment]
Considering your Apex "lifestyle" goals it seems like these pricing options might trap you in a business model that works against your overall business goals. Per-user, or any application level pricing models will require tracking licenses, license enforcement, lots of billing work (with associated chargebacks, etc) and a lot of small transactions best handled by a larger organization (at least larger than one person). A business/enterprise oriented model typically requires a sales team/person and much longer sales cycles. Many small startups starve to death before they can get the enterprise customer to finish their evaluations and budgetary cycles and get to a pay day.

In the short term, considering your large network/reach, what if you eliminated the Pro license and closed source headaches and funded the project using a Kickstarter? $1 tip jar, $30 t-shirt, $50 sponsor (name on website or something), $1,000 patron with some personal interaction, $5,000 spend a day with TJ, etc. Make the pro features "stretch goals". The goal is a "war chest" of cash up front without the hassle of actually running a business for the first 6 months to 1 year of the project. Maybe push to the open repo behind a 30 day delay with the actual working repo a private repo only exposed to kickstarter backers?

Spend the next X months building the solution using the kickstarter money, growing the user base, and finding the right corporate sponsor to fund further development. You can decide based on your needs whether that should just be a I'll-make-features-just-for-you sponsorship, brand-exposure-for-money sponsorship, or an employment sponsorship (ala node.js early vs late Joyent days).

Long term, partner with a consulting/support company to provide paid consulting/support (similar to Redis). If necessary, create a pro version at that point with the partner handling the gory details of licensing, billing, support, etc. (Again, ala Redis Enterprise).

**Comment by tj** [comment]
I don't think it has to be super complicated, Sidekiq bills annually so that takes out many of the headaches. I've tried the whole donation thing, it didn't really work, so I don't think I'll ever go that route again it just isn't sustainable. I'll definitely have to make sure to keep things as simple as possible, TBH I don't think Mike from Sidekiq even enforces the licenses, though at least with a private binary it's easy to restrict access there. 

You might be totally right that it could end up going against my lifestyle ideals, only one way to find out I guess! Maybe even having Pro OSS as well and just the honour system would be fine, companies don't seem to mind, individual developers tend to think they can quickly build any solution on their own, even if they're wasting hundreds of $$ doing so.

**Comment by badslug** [comment]
Keeping things simple and relying on the honor system is probably the right way to start. If you're really hurting from piracy then you can try to add some license security but as you say, it's probably not worth it.

I think Kickstarter would be great for marketing. It's also a nice way to bring in some early money. When Joyent used to need extra cash they would run an "unlimited lifetime" deal where you'd pay basically 2-3 years worth of hosting and get unlimited lifetime hosting. If the pro license is say $50/year you could run a kickstarter backer level that's something like $200 for an unlimited lifetime personal pro license (associated with a personal email addess).

I agree that scaling to company size is a good idea but could be hard to do while keeping things simple. Maybe have 2 "pro" levels and the free. Free lets you work on just one project at a time (somehow) or maybe doesn't come with the UI (it's command line only). Pro which can be very reasonably priced lets you have unlimited projects and/or the GUI. Both versions are pretty unlimited when it comes to the type of project and AWS resources you can use. 

The expensive version is an "Enterprise" edition. For Enterprise features, focus on concerns that only larger organizations have rather than trying to limit the actual ability to do real world commercial deployments or access/use certain AWS features? There are many things that only crop up if you have a large number of users (like audit trails), or if you want/need to enforce workflows. For example, approval workflows: a build has to get approval from any 2 QA people and at least one release manager before it can actually be deployed. That's something a small company doesn't need at all, but would be "business critical" for enterprises.

Anyway, sorry for the long rant - I'm really excited to see what you come up with!

**Comment by tj** [comment]
@badslug totally agree, much of that stuff is just a burden on smaller companies, and larger / enterprise workflows are definitely entirely different. I can't imagine anyone but small companies deploying locally via `up`, Pro users will likely be CI, and then Enterprise would be more like you mention. I like that split, Sidekiq does three as well, makes sense to me, I'll see what I can work out for features. Thanks again!

**Comment by maxbeatty** [comment]
What if `up` positioned itself more like a *tool* rather than a *service* that you had the option to continually pay for? [Sketch](https://www.sketchapp.com) is the closest example to borrow from. 

You could oversimplify Sketch as a glorified SVG editor and `up` as a glorified AWS API caller. Individuals could accomplish the final result of an SVG or API Gateway + Lambda by hand but it's much easier to use a specialized tool.

Sketch starts with a free trial so you can see all that it does. When you buy a Sketch license, you get one year of free updates (each license funds the continued development). If the version of Sketch you bought does everything you need, you never pay anything again. If you want to renew your license to get the latest features, you can do so at a discounted rate (encouraging ongoing support of Sketch). Volume discounts encourage companies to get a copy for everyone.

Replace "Sketch" with "`up`" in the previous paragraph and it's really appealing to me as a potential customer and perhaps meets most of your personal goals. (This model could also be applied to `apex` obviously.)

**Comment by tj** [comment]
#375

**Comment by nahtnam** [comment]
I know this is closed but I would like to provide an alternative pricing scheme. I would love it if I could pay you, and only you. What I mean is, I run `up` and it deploys to your AWS account. I should be able to add custom domains, env variables, whatever else through the website and not ever have to worry about looking at AWS. You can then just take the server cost from AWS, add x% and charge me for it. Why do this? Well because I don't want to mess with AWS. It's too complicated for me to worry about and if you could just do it for me, I'd be willing to pay a premium. Additionally, if you were to add Docker support (deploy Dockerfiles), you'd be filling a gap that Zeit left with their upgrade to v2. This is sort of how Zeit currently works and I really like the method. And if you are wondering if this system works, yes it does. Zeit does it, wordpress.com does it, Gitlab does it. Make the tool free and make money from simplifying peoples lives even more.

Interested to hear what you think. It may be too late to do anything now, but might be interesting should you decide to release a v2.

**Comment by tj** [comment]
@nahtnam appreciate the feedback, yeah it's certainly a possibility. I primarily chose to do it this way because most companies require (and prefer) the isolation for security purposes, and of course it shields me from malicious use since I'm not paying for the Lambda bill.

I'm personally not too interested in doing a PaaS version where I host everything, primarily because Heroku and others already exist, and they do nice job, and are actually cheaper than Zeit haha, even Zeit's logging would cost me $350/mo alone.

I'll definitely consider it though if it's something people really want, there are definitely some advantages to PaaS.

**Comment by badslug** [comment]
I think a simple affordable PaaS version would be super compelling - but a "run Up on your own AWS" option should always be in the mix for exactly the reasons you stated. 

If you didn't want to do all the ops work you could partner with someone or bring on an "employee #2" that just does that piece and lives (or dies) off the PaaS revenue.

**Comment by nahtnam** [comment]
You said it yourself. Most **companies** require isolation and this is where you charge money for a pro edition. If an enterprise wants a good but easy solution, they'd be more than willing to pay for it. For someone like me who just wants to host a few side projects and my portfolio, I really don't need that. I'd rather just pay a dollar or so to get it done. Currently, my monthly bill for Zeit is around $0.7 with around 500,000 requests a month with v1. However, v1 is set to die soon and Zeit has been pretty unstable for me so I would love to switch.

The only downside I see is that if you host it for us, we won't get the 1 million free requests :( If you get big enough though, you could possibly subsidize this for the free plan.

**Comment by lukeed** [comment]
There are many downsides to Up deploying your code on its account/servers. I thought about this initially too, but eventually agreed that the current model is the right choice for @tj's perspective. While it may be simpler on the user's end (dealing with AWS in any capacity is horrible, yes), TJ only inherits more cost and more liability. The price would have to increase to compensate, which a larger majority wouldn't be thrilled about.

This could still be offered, but IMO should be a separate, more expensive tier that users select.

**Comment by tj** [comment]
@nahtnam even a thousand people giving me $0.7 for side projects isn't worth it though :p that's the problem, it's maybe ok for startups where "growth" and hype is a metric that might help them sell the team in the future to some other company, but as an indie developer it's probably not a great choice.

**Comment by nahtnam** [comment]
Good point, in that case the current system works well! :)
