### ISSUE TITLE
Up doesn't work without a package.json

### ISSUE THREAD

**Issue by baptistemanson** [apex/up#242]
Hey everyone,

When I try the get started process with up, I can see in the logs:
4:45:10pm INFO starting name: task type: server
4:45:10pm INFO found free port 39091 version: $LATEST
4:45:10pm INFO executing "./server" version: $LATEST
4:45:10pm INFO waiting for http://127.0.0.1:39091 version: $LATEST
4:45:10pm ERRO sh: ./server: No such file or directory

How to fix the problem?
Add in the doc:
To create a package.json, you can:
```bash
 $ npm init
```
Then edit it to add a start script section, for instance:
```json
  {
   "scripts": {
    "start": "node index.js"
  }
}
```
I can do the PR if you think it is the correct way of fixing the problem.

**Comment by stephenmathieson** [comment]
Up tries to detect the necessary runtime for your project. If it finds a `package.json`, it knows to use node, and will default to running [`node app.js`](https://github.com/apex/up/blob/v0.1.10/config.go#L145-L146) if no "start" script is present. You can, of course, change this by adding an `up.json` file to configure Up.

**Comment by tj** [comment]
Closing for now, `scripts.start` and `app.js` are mentioned in the docs, as @stephenmathieson mention that's the default for now. I'm not sure `index.js` is a good name for a server, since a server (typically) doesn't export anything. Open to suggestions on the name, `app.js` is pretty arbitrary too!
