### ISSUE TITLE
Why express if FaaS/serverless?

### ISSUE THREAD

**Issue by gunar** [apex/up#244]
It seems [nodejs examples](https://github.com/apex/up-examples/blob/master/oss/node-express-browserify/app.js#L12) instantiate express/koa servers,
but I was expecting a simple `module.exports = function () {}`.

How am I wrong? Please enlighten me.

Thanks in advance.

**Comment by shanepelletier** [comment]
`up` allows you to program your functions as HTTP servers, so you can use the tools you're already used to using for web development. I'm not sure if support for "raw" functions like those in Serverless  is planned for the future, that's a question for @tj.

**Comment by tj** [comment]
The FaaS part (for Up at least) is just an implementation detail. I chose Lambda because it scales and is cost effective, but as more options become available I'll be supporting those.

Like @shanepelletier mentioned Serverless (and apex/apex) are more focused on function-level experiences, so they require new abstractions, and are harder to develop locally etc. Up is more focused on what most people already know how to do, developing with frameworks they know, via regular HTTP since that abstraction isn't going anywhere.

Personally I think routing etc is not much of a problem, which is why I prefer to just write my app as I normally would, without FaaS abstractions, but it depends what you're looking for :D. The nice thing about Up is that you can use what you already know (Express, Koa, Go's net/http, etc) and easily configure CORS, redirects, rewrites on top of that since Up provides a reverse proxy as well.

It's a good question though I'm sure I'll get this a lot so i'll try and do detailed comparisons in the docs.
