### ISSUE TITLE
Consider Adding Comparison to stdlib.com

### ISSUE THREAD

**Issue by bradledford** [apex/up#245]
Doing a comparison of Up to stdlib, there seems to be a lot of overlap and should probably be included in the comparison table. Some observations based on my cursory review:

- Stdlib looks to be a hosted-only service, whereas Up lets (requires) you to use your own IaaS account
- Stdlib has some seemingly nice local execution of services, allowing functions to be invoked immediately after creation. Up seems to want to deploy before invocation, albeit to a dev "environment." The lib CLI looks very effective at helping test newly created functions
- Type checking...there are some features in stdlib that enforce the type of function parameters. Not sure if Up has an opinion on this
- Stdlib has "fund-based" pricing, which might be annoying, forcing you to add money to your account to level up to different feature sets and account for spikes in usage. Unclear what happens when funds are exhausted.

**Comment by tj** [comment]
Can do. I have #6 so I'll keep leave as that one for now but the short version:

- stdlib (and Serverless etc) focus on function-level abstractions
- up focuses on app/api/site level abstractions

Up basically lets you develop as you normally would, because the apps it deploys are (literally) just your normal app. This means you can develop with `node app.js` locally, without knowing anything about Up. It's not as obvious as it could be since it's hosted in Lambda, but that's just an implementation detail. I'll try and clarify that in the docs :D

**Comment by bradledford** [comment]
Right on. I really do think the Up approach is superior, so was just thinking that the docs need to hammer that point home.

**Comment by tj** [comment]
Yeah I think the clarification is much needed haha, the mention of Lambda automatically makes you think of FaaS.
