### ISSUE TITLE
Default region

### ISSUE THREAD

**Issue by franciscocpg** [apex/up#250]
Comparing to tools like `aws-cli` or `serverless framework` for example, up is having a different behavior for default region.

If `AWS_REGION` is not set, before falling back to a hard coded region (`us-west-2` in up case) they search at  `AWS_CONFIG_FILE` (defaults to `~/.aws/config`) for `AWS_PROFILE` (defaults to `default`) for a `region` attribute.

May I propose a PR to achieve this same behavior?

**Comment by jlsjonas** [comment]
This is a confusing behaviour indeed; especially since the documentation kinda implies it would be followed

**Comment by tj** [comment]
I'm not fond of a `default` profile personally, seems like it would just be asking for trouble, I'd prefer people set up more explicit profiles for prod/dev named by project etc. Checking `~/.aws/config` sounds good to me though, but there's already so many ways to set things, I think it's excessive since the go-aws-sdk doesn't do this for you.

**Comment by franciscocpg** [comment]
hi @tj 
Please take a look at https://github.com/apex/up/pull/255.
