### ISSUE TITLE
Bearer Token Authorization?

### ISSUE THREAD

**Issue by mgoodings** [apex/up#287]
Does the reverse proxy prevent a parse through of the Authorization header and is there any way I can prevent it?

Used up for a small project for work to get a quick result and just stuck on this one piece.

I get a 502 on anything that is not a valid Basic Authorization header, trying to pass through a Bearer token.

**Comment by tj** [comment]
I'll double check, I know I don't have test coverage for it so it could be a bug. I believe API Gateway strips www-authenticate entirely,  not sure if it's a bug or they're trying to force people into using "custom authorizers". I'll look into it!

**Comment by kaihendry** [comment]
I'm hitting an issue where I get `{"message": "Internal server error"}` when I set the authorization header.  E.g.

    /tmp$ curl -H "authorization: bar" https://blah...blah/development/
    {"message": "Internal server error"}

That's without **and** with a custom authorizer set btw!

https://s.natalian.org/2017-09-13/without-custom.txt

Sidenote: Supporting custom authorizers would be super nice for my use case, since the "Result TTL in seconds" caching is super handy.

**Comment by mgoodings** [comment]
Issue was resolved for me too :)

**Comment by tj** [comment]
@kaihendry totally, for Up's built-in auth stuff I'll probably utilize that, I like the API Gateway plan-based rate limiting etc too, looks handy
