### ISSUE TITLE
.env for local env vars

### ISSUE THREAD

**Issue by tj** [apex/up#305]
- [ ] add `.env` file support
- [ ] add docs

**Comment by hhsnopek** [comment]
Maybe have `.env.{environment}` map to the environment it's deploying to? It'd also be pretty cool if it merged the `.env` files together and prioritized based on the environment.

Running `up deploy development` would use `BAZBAR`, instead of `bar`. `.env.staging` would do nothing because we're not deploying to staging.
```
.env
  FOO=bar
  KEY=baz

.env.staging
  KEY=FEE

.env.development
  FOO=BAZBAR
```

**Comment by tj** [comment]
yea maybe, I think for stage/prod it might be a little odd since most team members won't have the `.env` for those, only for local development

**Comment by hhsnopek** [comment]
I personally use them all the time haha, but we've found merging the two environments removes some good duplication

**Comment by tj** [comment]
that part makes sense to me, just wondering how many members of the team would have `.env.production` etc since it wouldn't be checked into GIT

**Comment by hhsnopek** [comment]
usually we pass those around via other means or commit "non-api-key" related materials in. `.env` doesn't just hold secrets in a couple cases

**Comment by tj** [comment]
ahh cool, I'll do a rough pass on this and we can see how it feels haha. It's a little tricky being one person, kind of have to just imagine how it'd be

**Comment by tj** [comment]
actually I suppose this is not really relevant, just need to document [.direnv](https://direnv.net/), but I guess `up start` could still support .env

**Comment by cgarvis** [comment]
All the projects I've been a part of that were not Rails, we used `.env` for local and set the environment vars in testing/staging/production by hand.  For my microservices, instead of writing code or using a library to load `.env` when in development, I've started to just run the command `source .env` when I open a new terminal.

**Comment by tj** [comment]
@cgarvis cool yea it's tempting to just tell people to use https://direnv.net/ hahah, it already does this

**Comment by tj** [comment]
think im going to close for now unless someone has a compelling argument
