### ISSUE TITLE
Add test cov and nicer error for missing / truncated body

### ISSUE THREAD

**Issue by tj** [apex/up#313]
Go's reverse proxy gives you stuff like `http: ContentLength=50 with Body length 0`, not bad but not a great message either

**Comment by skabbes** [comment]
1. Yes, should definitely do this.  However, I think the error `http: ContentLength=50 with Body length 0` is actually a symptom of something else.  I believe this errors happen when requests are retried (incorrectly).  Basically I think there is a bug in [Relay RoundTripper](https://github.com/apex/up/blob/b63c744a9d2304143810bdd309bfb1d269ded66b/http/relay/relay.go#L120-L151).

In that code, **non**-`net.Error` errors will be retried (once restarting the proxy is successful).  If _some_ of the response body has already been read (or all of it), and then you retry the request, you will not be able to read the body again (which is why you're seeing Length 0).

It seems that another go reverse proxy, traefik's [retry middleware](https://github.com/containous/traefik/blob/dae7e7a80a02535f0c1f07e9ebb7aedccc551276/middlewares/retry.go#L36-L43) has a possibly related problem - a double close. which I think could be a problem as well.

Maybe this isn't the right place to justify this, but if you read the details of [http.RoundTripper](https://golang.org/pkg/net/http/#RoundTripper), "RoundTrip must always close the body", "RoundTrip must return err == nil if it obtained, a response, regardless of the response's HTTP status code.".  It implies to me that `RoundTripper` as a retry mechanism isn't the best way to go, especially when paired with a `SingleHostReverseProxy`, which doesn't allow us the visibility into the handling of the request well enough to know for certain that we are complying with `RoundTripper` expected usage.

**Comment by tj** [comment]
@skabbes ahh damn yea that sounds not great haha, should have time to work on that today

**Comment by skabbes** [comment]
I have implemented this here:

https://github.com/apex/up/pull/334
