### ISSUE TITLE
Add upgrade --version flag or arg

### ISSUE THREAD

**Issue by tj** [apex/up#387]
Allowing users to maintain a specific version, this may be useful in the future for breaking changes.
  
- [ ] test with OSS
- [ ] test with Pro

**Comment by huangbong** [comment]
Yes, I also think this is very important (following from #421). Would also like to add that if you do `up upgrade` without a `~/.up/config.json` set, it will say "No updates available, you're good :)". It makes sense, because we don't want to upgrade non-pro users to pro but the problem is, when doing CI, I would like to have a pre-built image with up pro installed so I don't have to do `up upgrade` before every `up deploy`. I'm trying to work around this by running the curl install script `sh install.sh 0.1.9-pro` but it's not working because the binaries for the pro versions are not built on the releases page. Great to see env stuff finally out though and it looks like just having a version flag to upgrade will fix all of these problems.

**Comment by tj** [comment]
@huangbong noted! I'll open an issue for making the Pro install more direct

**Comment by cloudkite** [comment]
@tj nice work! How do we upgrade to specific version of pro? Does it need the pro suffix? ie 0.4.7-pro

**Comment by tj** [comment]
@cloudkite ah! good question haha, updating the docs for that, but if you're logged in and subscribed it'll always grab Pro
