### ISSUE TITLE
Task timed out after 18.01 seconds in us-west-2

### ISSUE THREAD

**Issue by kaihendry** [apex/up#395]
I have a lambda function that fetches some things on the network and puts that in a S3 bucket... and yes, it can run for more than 18s. This wasn't a problem in ap-southeast-1, but since deploying in us-west-2, I've struck this issue.

```
time ./remote-test.sh
HTTP/2 502
content-type: application/json
content-length: 36
date: Mon, 30 Oct 2017 08:55:46 GMT
x-amzn-requestid: 137e58fd-bd50-11e7-8987-517e92f930cf
x-cache: Error from cloudfront
via: 1.1 2ed072dcf3e5d253ca3caad233e07058.cloudfront.net (CloudFront)
x-amz-cf-id: dvdFtAbC1rqCt2lOb9GeUJWvWCIEyD1dAssVRQ8LiWXN9HFs7X9Eww==

{"message": "Internal server error"}
real    0m18.602s
user    0m0.025s
sys     0m0.014s
```
From `up logs`:

```
  6:55:25am INFO REPORT RequestId: 137f9168-bd50-11e7-973f-2f07cefa3cfe        Duration: 18018.19 ms   Billed Duration: 18000
ms      Memory Size: 512 MB     Max Memory Used: 45 MB
  6:55:25am INFO 2017-10-30T08:55:46.064Z 137f9168-bd50-11e7-973f-2f07cefa3cfe Task timed out after 18.02 seconds
```

Searching for "timeout" upon https://apex.github.io/up/#configuration ... I'm not sure if I can get around this. Can I return from the request and have a goroutine running for a minute or two, until the copy is done? Or am I basically stuck with moving to AWS batch at this point?

**Comment by tj** [comment]
Lambda itself has 5m limits, so you could use Lambda internally for more long-running stuff, but unfortunately for now API Gateway is limited to 30s, and we need a bit of "breathing room" within Up to timeout properly.

I'm hoping they'll increase the limit at Reinvent, but for now there's no way around the timeout they enforce :'(. Closing for now since it's not actionable, but if it's work which can be delayed I'd fire off an event to SNS and use Lambda to process those events

**Comment by kaihendry** [comment]
Made a video how I am struggling to find a nice paradigm for dealing with long running operations at work on this topic https://www.youtube.com/watch?v=vw4TJ7QnfXE
