### ISSUE TITLE
cn-north not supported yet?

### ISSUE THREAD

**Issue by gongzili456** [apex/up#446]
aws lambda supported cn-north now,

will up support ?

**Comment by tj** [comment]
From what I've read the cn-north region has restrictions, no env variables etc? I'll have to confirm, maybe it'll work fine and we can add it

**Comment by timqian** [comment]
If the `env variables` means setting `aws_access_key_id` `aws_secret_access_key` and `region`;
It works for aws-cli

**Comment by tj** [comment]
not seeing api gateway support for it here http://docs.aws.amazon.com/general/latest/gr/rande.html, closing for now

**Comment by timqian** [comment]
@tj API gateway is supported in China region. The information is documented in a separate table:
http://docs.amazonaws.cn/en_us/general/latest/gr/rande.html#cnnorth_region


I think this is due to the uniqueness of China region, China aws is separated to other regions, one has to register a new account if he want to use China aws.

**Comment by tj** [comment]
ohh wow yeah I totally missed that, interesting. I wonder if I can even sign up for an account to test, but as long as the APIs all work we should be able to add it.

**Comment by timqian** [comment]
@tj Cool, I will also have a test today, got a demo API need to be deployed on hand

**Comment by tj** [comment]
dup of #515
