### ISSUE TITLE
Make `up env` vars available locally for build and `up start`

### ISSUE THREAD

**Issue by tj** [apex/up#458]
Make the remote vars available so that build hooks can utilize `UP_STAGE` etc. Probably add `NODE_ENV` as a default there too.

- [ ] make them available to hooks
- [x] make them available to `up start`
- [ ] make them available to `up run` hooks?
- [x] add magical `NODE_ENV` (might as well)
- [ ] add debug logs for init
- [ ] refactor initialization logic (common across build, deploy, start)
- [ ] add example?
- [ ] QA
- [ ] document

**Comment by dominicbarnes** [comment]
This feature can't come soon enough! I keep having difficulty trying to run locally as well as after deploying without hacks.

**Comment by tj** [comment]
I'll try and get this in after this next release, or posssssibly part of this release

**Comment by tj** [comment]
I should mention for people who arrive here, https://direnv.net/ is pretty sweet for local env vars, but `up env`'s stuff should still show up

**Comment by tj** [comment]
done! will be in the next release

**Comment by tj** [comment]
I suppose one downside of this is that `up start` won't work offline, but one of the big points of Up is to just write regular apps, so you could just `go run main.go` etc. I guess we'll see if that gets annoying.

**Comment by tj** [comment]
@dominicbarnes what was your use-case again beyond `NODE_ENV`? I wonder if this is maybe overkill for `up start` and the build phases, I have mixed feelings about it haha.

**Comment by dominicbarnes** [comment]
amazing! I can't wait to try it out :)

**Comment by dominicbarnes** [comment]
@tj my main use-case is building my front-end code, as my server is not serving the assets dynamically. Specifically, I'm using a publicly accessible CouchDB server that both the front-end and the back-end communicate with.

Since `up start` is primarily a dev server, I could get by just using a default config, which is overridden when deployed. (but it would be kinda cool to mimic stages even when using `up start`)
