### ISSUE TITLE
[Question] Simple question about package name

### ISSUE THREAD

**Issue by kud** [apex/up#549]
Hello,

I've got a script which installs and maintains my machine up to date.

I used to do this: `$ npm install up -g` to install the cloudup cli but now, I've got your project instead. I was a bit 🤔  when I wanted to try my command `$ up`.

So... I would like to know, how did you get this project name in fact, by overriding the one from cloud up team?

**Comment by tj** [comment]
Yeah I reached out to Automattic like a year ago but they never got back to me, so I bumped the version, you can still install an older semver of course. 

Cloudup is basically a dead project, has been for years.

**Comment by kud** [comment]
Okay! Thank you for your answer and your time. ;)

**Comment by kud** [comment]
I installed it via `npm install -g Automattic/cloudup-cli`.

**Comment by kud** [comment]
In fact my question was mostly like there's no permission on npm? How did you override their packages?

**Comment by tj** [comment]
I wrote the original cli. Honestly I'd just move on to Droplr / Cloudapp etc haha they're a lot better anyway

**Comment by kud** [comment]
That's why! Okay I understand now. :)

**Comment by oskosk** [comment]
> Cloudup is basically a dead project, has been for years.

@tj this is not true. We use it extensively. It's not even free to maintain. Developers and Happiness Engineers (support crew) use it daily for different purposes. Even our documentation is packed with images coming from Cloudup. And the feature of having an `up` cli to rapidly upload and get a rapid URL for  a screenshot one has just made is **essential** for daily tasks.

> they haven't monetized it at all or changed anything, I don't think they have any intention of maintaining cloudup.

This is not quite an accurate way of inferring how the company has been using the product for years though. But I do understand the concern of course. Came here due to having received a notif for Automattic/cloudup-cli/issues/56

**Comment by kud** [comment]
Thanks @oskosk , I still use it to be fair. :D
