### ISSUE TITLE
options to avoid .upignore to pickup .gitignore by default?

### ISSUE THREAD

**Issue by zhenyulin** [apex/up#557]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

## Description

Just started to use `up` and was amazed by its simplicity. Wasn't aware that .upignore would pick up .gitignore by default until checked the examples after wondering why the built file isn't upload to Lambda.

Was thinking if it is more intuitive to have `.upignore` independent from `.gitignore` so that it wouldn't require the pre-knowledge that it would extend it by default. 

Furthermore, it helps to make it more explicit and doesn't need to check two files when it comes confirming the settings.

## further thought
can be very useful to have the feature as a separate module to make it possible to add ```@extend .gitignore```, can potentially be very useful to help manage `.dockerignore`, `eslintignore` as well

**Comment by tj** [comment]
I'd totally agree from a UX perspective that it can be confusing, my main concern is included sensitive files by accident which would normally be gitignored.

Definitely open to suggestions there, maybe it would be possible to make missing files a bit easier to troubleshoot, right now there's just `up -v` and `up build --size` which lists the contents.

**Comment by zhenyulin** [comment]
was thinking of possibly using "index" field in the config file so that it could be checked before deploy? currently it seems the run command would rely on "start" command in the `package.json`. This might help to make this independent from `package.json`.

**Comment by tamagokun** [comment]
I tend to agree with this. What you explicitly store in the repo isn't necessarily what you are trying to package for a deployment to Lambda. I'd say that a lot of projects beyond simple examples will have some kind of build step, which would result in output that would most likely be in `.gitignore` therefore also needing to get added to `.upignore` as negated (`!./build`).

I don't know how many times i've bashed my head on the keyboard because my deployment didn't work and then, aha! .upignore!

I see a few options here:

1. Keep the .upignore route, ignore dotfiles by default, and any language specific defaults (i.e. node_modules).

2. Use a `"files"` convention similar to that of package.json to whitelist what files should be included in the deployment. If files isn't provided, it uses everything. (maybe ignore dotfiles by default here too)

**Comment by tj** [comment]
Yeah I think those are valid points, sensitive stuff tends to be in dotfiles. My intention was to avoid any sketchy files from being uploaded, but I can't really think of any off-hand which would be non-dotfiles. We can try changing this and if anyone has a compelling reason to revert, then not a big deal.
