### ISSUE TITLE
Remove "development" stage

### ISSUE THREAD

**Issue by tj** [apex/up#563]
Right now the "development" stage is a little confusing for a few reasons:

I wouldn't really call anything running live dev, dev == local to me, but it used to utilize $LATEST in Lambda so it made a bit more sense at the time.

Also now you can do the following to override `up start`'s local command, however this is _also_ what will run in Lambda, which is confusing.

```
{
  "name": "app",
  "stages": {
    "development": {
      "proxy": {
        "command": "gin --port $PORT"
      }
    }
  }
}
```

Also we just really don't need two staging envs haha... later if we have custom stages then you could do whatever you like of course. 

## Changes

- Remove "development" and treat `up` as "staging"
-  If you have a `development` stage mapped to a domain already you will have to change it to `staging`
- `up env`'s vars mapped to "development" will be used for `up start` only

## Work

- [x] Default to "staging"
- [x] Remove mention of "development" aside from local use
- [ ] QA `up start` env vars
- [ ] Update examples repo
- [ ] Update old blog posts

## Votes

[![](https://api.gh-polls.com/poll/01C56SV8N7DBH3FSTCYSAB9EN7/Remove%20development%20env)](https://api.gh-polls.com/poll/01C56SV8N7DBH3FSTCYSAB9EN7/Remove%20development%20env/vote)
[![](https://api.gh-polls.com/poll/01C56SV8N7DBH3FSTCYSAB9EN7/Keep%20it%20and%20change%20the%20default%20for%20%60up%60%20to%20staging)](https://api.gh-polls.com/poll/01C56SV8N7DBH3FSTCYSAB9EN7/Keep%20it%20and%20change%20the%20default%20for%20%60up%60%20to%20staging/vote)
[![](https://api.gh-polls.com/poll/01C56SV8N7DBH3FSTCYSAB9EN7/Keep%20it%20as-is)](https://api.gh-polls.com/poll/01C56SV8N7DBH3FSTCYSAB9EN7/Keep%20it%20as-is/vote)

**Comment by kaihendry** [comment]
Argh, just hit this whilst going out my mind since my endpoint was not updating.

Replacing `development` with `staging` in my **up.json**'s domain stanza doesn't seem to do the trick.  Even after `up stack apply` I hit a `already exists in stack arn:aws:cloudformation:ap-southea...`

Bring down the stack is especially painful since I have policies attached to the role. Now CloudFront seems to be just hanging trying to rebuild the stack.

![a](https://user-images.githubusercontent.com/765871/36369194-4d942b36-1595-11e8-9c2a-e4f2c6e81643.png)


Is there some easier migration strategy I am missing ? :sob:

**Comment by tj** [comment]
@kaihendry CloudFormation seems like it doesn't understand one is removed and another is created—Terraform handled this kind of thing fine :(— I think you may have to remove development from up.json and `up stack plan` / `up stack apply` and then add `staging`

**Comment by kaihendry** [comment]
Downtime for route53 records to be updated is really quite painful whilst CloudFormation is **UPDATE_IN_PROGRESS**.

Is it a reasonable workaround to not manage domains in up.json and just manually update *custom-domain-names*, to minimise downtime? I guess the con is that my domain isn't managed anymore by CloudFormation. Not a bad thing since now at least have some control and I can switch with no downtime.

**Comment by kaihendry** [comment]
Oh btw, do the docs need updating https://up.docs.apex.sh/#configuration.stages ?

**Comment by tj** [comment]
Yeah it's not ideal but I can't see too many people swapping `production`'s domain, so I guess worst-case of a bit of downtime for staging is bad, but not as bad, I don't want to get too crazy with encouraging manual work if it can be avoided.

I heard a rumour that CloudFront's propagation will be "instant" sometime soon too, I realllllly hope that's true 😄
