### ISSUE TITLE
Python 3.4 as default

### ISSUE THREAD

**Issue by tj** [apex/up#576]
Right now you need to do: https://github.com/apex/up-examples/tree/master/oss/python-3.4—however I imagine this should be the default. And we can have `runtime: "python2.7"` or something

[![](https://api.gh-polls.com/poll/01C62XCFW5TS5V67FV7ZXYNDP1/Python%203.4)](https://api.gh-polls.com/poll/01C62XCFW5TS5V67FV7ZXYNDP1/Python%203.4/vote)
[![](https://api.gh-polls.com/poll/01C62XCFW5TS5V67FV7ZXYNDP1/Python%202.7)](https://api.gh-polls.com/poll/01C62XCFW5TS5V67FV7ZXYNDP1/Python%202.7/vote)

**Comment by lukeed** [comment]
Voted yes, but I think the official "migration" stance is to have a `python3` binary separate from `python`, so more die-hard Pythonists may expect to see that?

In any event, I think the `runtime` config is confusing, unless every language is going to have that ability. Specifying `python2|3 app.py` as the command seems clear enough.

**Comment by komuw** [comment]
voted yes also mainly because I would like to see more python3 adoption and a lot of tools/OSes making py3 default is going to help. 

But I think the default should be whatever the default python version is in most people's OSes; ie for most people, when they type in `python` on their terminal, what version shows up? I think that is what `up` should default to, unless `up` wants to join in the fight to move people forward

**Comment by tj** [comment]
@lukeed ahhh yeah that would make sense, if it's the norm then that would be pretty confusing to change, I guess it depends on adoption rate too if most people are still on 2.x or what.

I like the idea of runtimes over commands, because it just gives us a bit more flexibility later to alter the Lambda `runtime` as well, instead of always assuming a Node.js runtime, which just happens to have Python on it (and works for binaries of course).

**Comment by tj** [comment]
yea nvm, closing this, didn't realize `python3` as a bin name was the norm
