### ISSUE TITLE
Question: context.callbackWaitsForEmptyEventLoop support in node.js

### ISSUE THREAD

**Issue by h2non** [apex/up#587]
Apparently, in node.js runtime on AWS Lambda, setting `context.callbackWaitsForEmptyEventLoop = false` will allow having a shared global state within the node process across multiple function invocations, which can be useful for shared connection to DBs etc...

Do we have it enabled by default? 
Is it possible to enable? 
Does it make sense what I'm asking here?

Thank you!

**Comment by tj** [comment]
Ahh it is disabled because Node.js (runtime-wise) is only used for the shim. How it looks in practice with Up is:

```
event from API Gateway -> Node.js shim sends the event to Up's Golang proxy -> sends HTTP request to your application (Node, Python, Golang, etc)
```

So because of that setup, only the Node.js shim actually has `callbackWaitsForEmptyEventLoop` available to it, so I don't think it's possible right now. Althoughhhh I had heard rumours that Lambda may be getting new features to make it more async-work friendly

**Comment by tj** [comment]
closing since it's not possible for now

**Comment by kuka** [comment]
Any news on this?

**Comment by tj** [comment]
@kuka not at the moment, it seems like a weird feature to me, since it would be an anti-pattern to not invoke the callback when the work is done. Lambda itself isn't great for background work, you pretty much have to fire off another async function or queue to do the bg work elsewhere
