### ISSUE TITLE
[Questions] - Up viability for production, backing team/organizations

### ISSUE THREAD

**Issue by jhalborg** [apex/up#641]
Hey, 

First of all, this library and the idea behind it is amazing, and the speed at which you develop it and answer issues is amazing - keep it up!

I'm looking for the best way to manage the deployment of my Express.js app to AWS Lambda, and came across this pr recommendations in the Graphcool sphere. I'm evaluating tools for production use for a rewrite of an existing platform that has thousands of users as well as large enterprise clients. 

Although the tool looks amazing, I can't help but be a bit afriad of the future support. If anything were to happen to TJ, who would drive this project forward? Are there any organizations or teams backing the project, either now or in the pipeline? If not, I can't justify using it yet, unfortunately :-/

**Comment by tj** [comment]
Hey!

I think that's certainly a valid concern, and one of the motivators behind #504, however, I would also say that since Up's goal is to let you deploy "vanilla" HTTP servers, it would be an annoyance but not a huge problem to migrate to something like Heroku or AWS ECS/Fargate etc if necessary. Another nice aspect is that since it's effectively a wrapper around AWS, you can easily get AWS support for runtime related problems, so if you're happy with Up as-is, it would continue to work as it does even if something happened to me.

Statistically I think it's far more likely for startups running PaaS will "die", it's rare that they last more than 3-5 years, I plan on being alive longer than that :D. Long-term I'd like to have a backup plan there, at least to hand my work's source over to someone or a company which can open-source it or continue building on it.

**Comment by jhalborg** [comment]
Hey!

Thanks, and sure - there would be ways to move forward, but that's the case as long as you use a standard Express app and any other deployment CLI. [Amazon's own Express-to-lambda-gateway CLI](https://github.com/awslabs/aws-serverless-express) looks somewhat promisin, for example. One could argue more 'lockin', but the counter would be the same as what you're saying - it'd be fairly manageable to switch deployments and be done with it. With that package, though,  we woudn't rely on one individual, in spite of him being as productive and smart as you are ;-) 

In regards to statistics, it wouldn't necessarily be the case of you dying or falling seriously ill (knock-on-wood) - maybe you had kids or something else changed your priorities in life. 

I guess I'm asking, if you were in my chair evaluating tech choices for the stack of a new platform, why would you choose Up over alternatives like the one mentioned?

**Comment by tj** [comment]
I think it mostly comes down to your own preferences, I personally feel better with larger companies like AWS, but that's why I decided to create Up, I don't like relying on startups which are almost guaranteed to fail in the near-future.

I definitely need to think of some backup plan there, someone who could take over in that case or maybe all the source would go to a foundation. Open to ideas to what would make people like yourself feel more comfortable about using indie stuff! I think indies are more sustainable, but like you say it's always a potential problem.

I wouldn't worry about it too much if you like what it provides, since it really is just a relatively thin layer on AWS, which is kind of by-design. I know if I created some PaaS by myself then yeah people are really locked in, but everything I use is vanilla AWS, and if it works now it'll continue to work unless they get really aggressive deprecating APIs which isn't their style.

**Comment by anzellai** [comment]
Very happy with Up at the moment and I’m in exactly the same boat as @jhalborg — evaluating tools to assist our internal migration to AWS stacks.

I wouldn’t worry too much about Up’s continuation as @tj has explained, I do believe a more stabilised foundation will increase corporate confidence in choosing Up as their mid-long term solution though.

@tj please let us know which way you’d prefer to bring this project forward, the community would help you on this :-)

**Comment by jhalborg** [comment]
Good to hear, @anzellai - I have no doubt this is a great tool, and I understand and agree with your arguments @tj . For the project I'm working on, however, the powers that be decided to go with Zeit Now, at least for now (heh). 

Best of luck to you, maybe I'll return for my next project :-)
