### ISSUE TITLE
Universal Now

### ISSUE THREAD

**Issue by thangngoc89** [apex/up#69]
I just see this https://zeit.co/blog/universal-now
Any comparisons?

**Comment by tj** [comment]
Haha saw that, I see they took inspiration from my Up blog post! Honestly it might not be sustainable to compete with a privileged startup, I'll give it some thought but long-term it would be hard to compete with a large team copying you.

**Comment by deiga** [comment]
But of course competition creates opportunity and provides a "sanity check" for services :)

Dependeing if you want to base your livelyhood on `up(1)` or not, this might be a good thing :)

**Comment by thangngoc89** [comment]
> That said they're still fallowing anti-patterns like the CRUD methods etc.

I might not understand how up works internally. Could you shed some lights? From their docs, with node.js they provide a standard `(req, res)` method to handle like this.

```
require("http")((req, res) => {

})
```

They said it's compaitable to node API

**Comment by tj** [comment]
@thangngoc89 they're doing the same local proxy technique that I highlighted in my blog post, which is what Up does as well, letting you run a vanilla Node / Python / Go server etc.

**Comment by thangngoc89** [comment]
@tj I've missed that blog post. Gotta dig that

**Comment by arikfr** [comment]
Competing with a funded startup is possible and it's not much differen than competing with any other competitor. Their ability to give away things for free is irrelevant as your pricing model is going to be affordable regardless. 

While Zeit build beautiful interfaces (GUI and CLI), they still far from offering the cohesive experience you plan on offering. They might  eventually catch up with some of it, but you will be already ahead in the game and have a good core user base. 

A good example for a company that played against funded startups and outlived most of them is Doist (the makers of Todoist and now Twist). They are in a super competitive space (todo apps) where most startups struggle to find a good business model as they need to satisfy VC expectations. They didn't have those expectations but just built a sustainable business that can provide for 50 employees.

**Comment by lukeed** [comment]
> Honestly it might not be sustainable to compete with a startup.

TBH, I wouldn't shut your own door until you've let this breathe for a bit. I use Now & will likely continue to use both when Up is released. In my experience, the UX of Now has been amazing, but the service itself has had its flaky periods & there are still quite a few unanswered questions in my (and a lot of others') book.

Assuming that it _is_ only hype they have to care about, then you have the advantage in that you can focus on the product. (FWIW I think they focus on product too, just not 100%.) Product outlasts hype; you'll win that long-game. And if there is a Now acquisition, in my exp, there's always a customer shuffle. Parent company ramps up pricing, removes features, or just does nothing in a year. Some percentage of customers nearly always leave -- you'll gobble 'em up!

Oh, and you can always _not_ blog post 😉

**Comment by rafaelamorim** [comment]
Well... i've been waiting to use up for a little long now.
After finding out about Now Universal, i honestly don't care! I prefer what i'm seeing here! 🥇 
The only point is that is taking a little bit too long... when i'll be finally able to use this AWESOME tool?

Competition exists in any market, they are neither good nor bad, they just exist! 
The important part is that there should be a demand for this, and, as someone looking forward to pay for this, i honestly don't think this is even a issue :)

Keep on with the awesome work @tj and apex's team! 👍

**Comment by tj** [comment]
Thanks guys. Obviously I chose to enter their territory haha, figured they'd stick with their own janky hosting service. Not sure if it's worth having two of these if they're going to be so similar. I'll think about it!

**Comment by tj** [comment]
Dev related tooling is probably just a bad place to be for someone like me, who wants to work ~4 hours a day and actually have a life. Although UX seems to be slightly unique to fewer programmers, it's definitely no technical feat, thus easily replicated.

**Comment by bentranter** [comment]
I think an overlooked part of dev tooling is how much the customers trust the company. I've ended up choosing IaaS providers with similar features, pricing, etc, before just based on the experiences I've had meeting their teams at conferences, reading their blog posts, following their OSS work, etc.

I think in the case of `up(1)`, people will use it just because they trust @tj over ZEIT. I know I will, and I'm assuming a lot of the people that've been following these issues and discussions feel the same way.

**Comment by tj** [comment]
I'm not sure it's a smart move, truthfully it's a really simple product since it delegates everything to the providers. I'm kind of shocked they've moved at the slow pace that they have, but that won't last forever with startup $$ and I don't plan on ever being more than a solo company, it was probably a bad idea to enter the space. I'll give it the night and decide, might just open-source what I have and call it a day

**Comment by stevelacy** [comment]
At the very least I'd suggest seeing who would signup for paid plans. Gitlab is a close call to github, and has self-hosted as well as paid hosted resources.

**Comment by tj** [comment]
@stevelacy yeah maybe, I don't doubt that it could work for the short-term. There's very little that is special about Up or ZEIT, they just seem sweet because "serverless" is so new, but it's super obvious that this is the future all products are converging on, it's just a matter of time.

Personally I think this kind of product does not belong in startup-land at all, it doesn't need more than one person, but startups can deliver bigger blows as far as making everything free etc with all that money.

**Comment by tj** [comment]
The part I get a kick out of, is that they even think it's startup material. I takes time sure, but this is the most basic stuff you can write. How unique, you type a command and something gets deployed, amazing.

**Comment by tj** [comment]
hahah yea it's like a straight up clone of my blog post, local proxy server in the Lambda's etc. Nicely done

**Comment by arikfr** [comment]
What blog post?

**Comment by FrancosLab** [comment]
I believe in this project. Just vibe.

**Comment by olivoil** [comment]
I would probably use `up` with a paid subscription, even if they offer a similar-ish product for free. And I would probably not use their product, even if `up` doesn't see the light of day. I've been using tools and oss libraries you wrote for years, and you've consistently been able to produce things that work well and have become indispensable to me. `apex.run` is one of them, and from what you've released about `up`, it sounds like it would be another one too.

Speaking for myself here, but I'm sure others share the same opinion. You have my vote of confidence, and I'd love to see what you do with `up`.

I don't know if it will be enough to win market share against a funded startup with a different exit strategy on users who don't know you in the first place. But it'd be great if it's enough to slowly but progressively grow a profitable business.

**Comment by maxbeatty** [comment]
Like others, I see the competition as a good thing and not a "winner take all" situation. Both tools are trying to simplify managing cloud resources by abstracting it through a CLI. 

I see Zeit's offering as a funnel to their cloud offering. If developers are comfortable with `now` and come across a use case that can't be met by functions-as-a-service, then it would be easiest to get a premium account to host long-running processes from the same CLI (instead of dive into AWS or GCP which they might not understand since all the details have been abstracted away).

I posted a [comment](https://github.com/apex/up/issues/2#issuecomment-315452769) in #2 on a pricing strategy that might sustain an independent solo operation. I still see a lot of value in `up` being released!

**Comment by loganpowell** [comment]
I feel like there's a great story behind this feud. Someone (cough, @tj, cough) should write up a blog post exposing the under-belly of Silicon Valley. I mean Zuckerberg stole his ideas from the Winkelvoss bros, Jobs lifted his GUI from Zerox, Gates at least bought his first OS (albeit for pennies on the dollar) from Gary Kildall. Why do I feel there's a pattern here?

**Comment by loganpowell** [comment]
> It's much harder to make $10k/mo than it is to make $5M in VC funding.
💯
